config/routes.rb
Rails.application.routes.draw do
  devise_for :clients, controllers: {
          registrations: 'clients/registrations'
        }

  devise_for :users
        
  get 'clients/get_coordinates'
  get 'companies/index'
  get 'mytrucks' => 'trucks#mytrucks'


  resources :trucks
  resources :companies
  resources :products
  

  resources :products, only: [:index, :show] do
    resources :requests, only: [:create]
  end

  resources :requests, except: [:create]
  root 'products#index'

 # devise_for :clients
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/truck.rb
class Truck < ApplicationRecord
	has_many :product_trucks
	has_many :products, through: :product_trucks
	belongs_to :company
	has_many :user_trucks
	has_many :product_companies
	has_many :products, through: :product_companies
	geocoded_by :address


end

app/controllers/trucks_controller.rb
class TrucksController < ApplicationController
  before_action :set_truck, only: [:show, :edit, :update, :destroy]
  before_filter :authenticate_user!, except: [:index, :show, :update]
  

  # GET /trucks
  # GET /trucks.json
  def index
    @trucks = Truck.all
  end

  def mytrucks      
    @trucks = current_user.trucks   
  end

  # GET /trucks/1
  # GET /trucks/1.json
  def show
  end

  # GET /trucks/new
  def new
    @truck = Truck.new
  end

  # GET /trucks/1/edit
  def edit
  end

  # POST /trucks
  # POST /trucks.json
  def create
    @truck = Truck.new(truck_params)

    respond_to do |format|
      if @truck.save
        format.html { redirect_to @truck, notice: 'Truck was successfully created.' }
        format.json { render :show, status: :created, location: @truck }
      else
        format.html { render :new }
        format.json { render json: @truck.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /trucks/1
  # PATCH/PUT /trucks/1.json
  def update
    respond_to do |format|
      if @truck.update(truck_params)
        format.html { redirect_to @truck, notice: 'Truck was successfully updated.' }
        format.json { render :show, status: :ok, location: @truck }
        format.js
      else
        format.html { render :edit }
        format.json { render json: @truck.errors, status: :unprocessable_entity }
        format.js
      end
    end
  end

  # DELETE /trucks/1
  # DELETE /trucks/1.json
  def destroy
    @truck.destroy
    respond_to do |format|
      format.html { redirect_to trucks_url, notice: 'Truck was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_truck
      @truck = Truck.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def truck_params
      params.require(:truck).permit(:name, :company_id, :longitude, :latitude, :address)
    end
end

app/helpers/trucks_helper.rb
module TrucksHelper
end

app/views/trucks/_form.html.erb
<%= form_for(truck) do |f| %>
  <% if truck.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(truck.errors.count, "error") %> prohibited this truck from being saved:</h2>

      <ul>
      <% truck.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  
<div class="field">
      <%= f.label :company_id,"Compañia", :class => "h4" %><br />
      <%= f.collection_select(:company_id, Company.all, :id, :name,{prompt: "Elegir Compañia"}, :class => "form-control")%>
  </div>
  
  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

   <div class="field">
    <%= f.label :latitude %>
    <%= f.text_field :latitude %>
  </div>

   <div class="field">
    <%= f.label :longitude %>
    <%= f.text_field :longitude %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/trucks/edit.html.erb
<h1>Editing Truck</h1>

<%= render 'form', truck: @truck %>

<%= link_to 'Show', @truck %> |
<%= link_to 'Back', trucks_path %>

app/views/trucks/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Trucks</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @trucks.each do |truck| %>
      <tr>
        <td><%= truck.name %></td>
        <td><%= link_to 'Show', truck %></td>
        <td><%= link_to 'Edit', edit_truck_path(truck) %></td>
        <td><%= link_to 'Destroy', truck, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Truck', new_truck_path %>

app/views/trucks/mytrucks.html.erb
<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Address</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @trucks.each do |truck| %>
      <tr>
        <td><%= truck.name %></td>        
        <td><%= link_to 'Show', company %></td>
        <td><%= link_to 'Edit', edit_company_path(company) %></td>
        <td><%= link_to 'Destroy', company, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/trucks/new.html.erb
<h1>New Truck</h1>

<%= render 'form', truck: @truck %>

<%= link_to 'Back', trucks_path %>

app/views/trucks/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @truck.name %>
</p>

<%= link_to 'Edit', edit_truck_path(@truck) %> |
<%= link_to 'Back', trucks_path %>
<%= link_to 'Mis camiones', trucks_path(@truck.company.id) %>

 