config/routes.rb
Rails.application.routes.draw do
  devise_for :clients, controllers: {
          registrations: 'clients/registrations'
        }

  devise_for :users
        
  get 'clients/get_coordinates'
  get 'companies/index'
  get 'mytrucks' => 'trucks#mytrucks'


  resources :trucks
  resources :companies
  resources :products
  

  resources :products, only: [:index, :show] do
    resources :requests, only: [:create]
  end

  resources :requests, except: [:create]
  root 'products#index'

 # devise_for :clients
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/request.rb
class Request < ApplicationRecord
	belongs_to :client
	belongs_to :product
	geocoded_by :address 
end

app/controllers/requests_controller.rb
class RequestsController < ApplicationController
  before_action :set_request, only: [:show, :edit, :update, :destroy]


  # GET /requests
  # GET /requests.json
  def index
    @truck = Truck.first
    @requests = Request.near(@truck.latitude, @truck.longitude, 10, units: :km)

  end

  # GET /requests/1
  # GET /requests/1.json
  def show
  end

  # GET /requests/new
  def new
    @request = Request.new
  end

  # GET /requests/1/edit
  def edit
  end

  # POST /requests
  # POST /requests.json
  def create

    @product = Product.find(params[:product_id])
    @request = Request.new(request_params)
    @request.product = @product
    @request.latitude = current_client.latitude
    @request.longitude = current_client.longitude

    respond_to do |format|
      if @request.save
        format.html { redirect_to root_path, notice: 'Request was successfully created.' }
        format.json { render :show, status: :created, location: @request }
      else
        format.html { render :new }
        format.json { render json: @request.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /requests/1
  # PATCH/PUT /requests/1.json
  def update
    respond_to do |format|
      if @request.update(request_params)
        format.html { redirect_to @request, notice: 'Request was successfully updated.' }
        format.json { render :show, status: :ok, location: @request }
      else
        format.html { render :edit }
        format.json { render json: @request.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /requests/1
  # DELETE /requests/1.json
  def destroy
    @request.destroy
    respond_to do |format|
      format.html { redirect_to requests_url, notice: 'Request was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_request
      @request = Request.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def request_params
      params.require(:request).permit(:latitude, :longitude)
    end
end

app/helpers/requests_helper.rb
module RequestsHelper
end

app/views/requests/_form.html.erb
<%= form_for(request) do |f| %>
  <% if request.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(request.errors.count, "error") %> prohibited this request from being saved:</h2>

      <ul>
      <% request.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :latitude %>
    <%= f.text_field :latitude %>
  </div>

  <div class="field">
    <%= f.label :longitude %>
    <%= f.text_field :longitude %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/requests/edit.html.erb
<h1>Editing Request</h1>

<%= render 'form', request: @request %>

<%= link_to 'Show', @request %> |
<%= link_to 'Back', requests_path %>

app/views/requests/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Requests</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Size</th>
      <th>Latitude</th>
      <th>Longitude</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @requests.each do |request| %>
      <tr>
        <td><%= request.product.brand %></td>
        <td><%= request.product.size %></td>
        <td><%= request.latitude %></td>
        <td><%= request.longitude %></td>
        <td><%= link_to 'Edit', edit_request_path(request) %></td>
        <td><%= link_to 'Destroy', request, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Request', new_request_path %>

<script>
  setInterval(getLocation, 1000)

  function updatePosition(position){
    console.log("hola");

    $.ajax({
      url: '/trucks/<%= @truck.id %>',
      type: 'PATCH',
      dataType: 'script',
      data: {'truck': {latitude: position.coords.latitude, longitude: position.coords.longitude}}
    })
    .done(function() {
      console.log("success"); 
   })
    .fail(function() {
      console.log("error");
    })
    .always(function() {
      console.log("complete");
    });
    
  }

  function getLocation() {
    if (navigator.geolocation) {
        navigator.geolocation.getCurrentPosition(updatePosition);
    } else {
      console.log("error");
        x.innerHTML = "Geolocation is not supported by this browser.";
    }
  }

</script>

app/views/requests/new.html.erb
<h1>New Request</h1>

<%= render 'form', request: @request %>

<%= link_to 'Back', requests_path %>

app/views/requests/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Latitude:</strong>
  <%= @request.latitude %>
</p>

<p>
  <strong>Longitude:</strong>
  <%= @request.longitude %>
</p>

<%= link_to 'Edit', edit_request_path(@request) %> |
<%= link_to 'Back', requests_path %>